version: "3"

services:
  clef-1:
    image: ethersphere/clef:0.5.0
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=100
    volumes:
      - /root/swarm/clef/clef-1:/app/data
    command: full

  clef-2:
    image: ethersphere/clef:0.5.0
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=100
    volumes:
      - /root/swarm/clef/clef-2:/app/data
    command: full

  clef-3:
    image: ethersphere/clef:0.5.0
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=100
    volumes:
      - /root/swarm/clef/clef-3:/app/data
    command: full

  node-1:
    image: ethersphere/bee:1.0.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE=false
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS="*"
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY=10000000
      - BEE_DB_OPEN_FILES_LIMIT=1000
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ENABLE=true
      - BEE_DEBUG_API_ADDR=127.0.0.1:10002
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR=47.241.251.39:10001
      - BEE_VERBOSITY=5
      - BEE_TRACING_ENABLE=true
      - BEE_SWAP_ENABLE=true 
      - BEE_SWAP_ENDPOINT=http://192.168.0.131:8545
      - BEE_PASSWORD=ju765dRi
      - BEE_FULL_NODE=true
      - BEE_SWAP_INITIAL_DEPOSIT=0
      - BEE_WELCOME_MESSAGE=工作定局小组
      - BEE_NETWORK_ID=1
      - BEE_MAINNET=true
    ports:
      - "${API_ADDR:-10000}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-10001}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:10002}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /root/swarm/bee/node-1:/home/bee/.bee
    command: start
    depends_on:
      - clef-1

  node-2:
    image: ethersphere/bee:1.0.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE=false
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-2:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS="*"
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY=10000000
      - BEE_DB_OPEN_FILES_LIMIT=1000
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR=127.0.0.1:10005
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR=47.241.251.39:10004
      - BEE_VERBOSITY=5
      - BEE_TRACING_ENABLE=true
      - BEE_SWAP_ENABLE=true 
      - BEE_SWAP_ENDPOINT=http://192.168.0.131:8545
      - BEE_PASSWORD=ju765dRi
      - BEE_FULL_NODE=true
      - BEE_SWAP_INITIAL_DEPOSIT=0
      - BEE_WELCOME_MESSAGE=工作定局小组
      - BEE_MAINNET=true
      - BEE_NETWORK_ID=1
    ports:
      - "${API_ADDR:-10003}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-10004}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:10005}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /root/swarm/bee/node-2:/home/bee/.bee
    command: start
    depends_on:
      - clef-2

  node-3:
    image: ethersphere/bee:1.0.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE=false
      - BEE_CLEF_SIGNER_ENABLE=true
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-3:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS="*"
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY=10000000
      - BEE_DB_OPEN_FILES_LIMIT=1000
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR=127.0.0.1:10008
      - BEE_DEBUG_API_ENABLE=true
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_NAT_ADDR=47.241.251.39:10007
      - BEE_VERBOSITY=5
      - BEE_TRACING_ENABLE=true
      - BEE_SWAP_ENABLE=true 
      - BEE_SWAP_ENDPOINT=http://192.168.0.131:8545
      - BEE_PASSWORD=ju765dRi
      - BEE_FULL_NODE=true
      - BEE_SWAP_INITIAL_DEPOSIT=0
      - BEE_WELCOME_MESSAGE=工作定局小组
      - BEE_MAINNET=true
      - BEE_NETWORK_ID=1
    ports:
      - "${API_ADDR:-10006}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-10007}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:10008}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - /root/swarm/bee/node-3:/home/bee/.bee
    command: start
    depends_on:
      - clef-3

volumes:
  clef-1:
  clef-2:
  clef-3:
  node-1:
  node-2:
  node-3:
